### ISSUE TITLE
arrange shortcut on panel

### ISSUE THREAD

**Issue by figihiuy** [chsh2/nijiGPen#13]
Hi

As a request, is it possible to place an icon on the panel that can perform an alignment that can be used when in edit mode?
I would like to be able to use it easily when I want to change the front/back position like in vector software.

Thanks for the great add-on software.

![image](https://user-images.githubusercontent.com/69837796/219291697-3f003826-a252-4be5-bd21-e88d046fae15.png)

**Comment by b4zz4** [comment]
@figihiuy can add a shortcut to "Send to Back" for example pageDown
Another option is to put it in favorites.

![2023-02-16_10-38_54](https://user-images.githubusercontent.com/643833/219380391-dafb0f45-f7ba-490c-b880-e98b5bc31fd2.jpg)

Both options work with right button

**Comment by chsh2** [comment]
![image](https://user-images.githubusercontent.com/110356534/219546796-1d9280a9-244e-491d-b316-3a7b31dbc842.png)
I think I can do it in a similar way as adding these extra undo/redo buttons. In the next version I will add more options of these buttons, including the arrangement.

For further consideration, I may need to redesign this panel in the future to make it more convenient, taking some mobile/tablet apps as references.

**Comment by figihiuy** [comment]
@b4zz4 Thanks for the info.
I knew about the quick shortcuts, but requested them because the on-screen buttons are easier to operate in a tablet pen environment.

@chsh2 I am looking forward to it. Thank you!

**Comment by chsh2** [comment]
https://user-images.githubusercontent.com/110356534/226196825-b4d0fb22-c2a3-4a0a-95a3-fa602bfc4561.mp4


I tried to move the shortcut buttons to the 3D view. I also added a new button allowing users to arrange strokes by dragging. I may need some time for debugging before the formal release, but the source code has already been available.
