### ISSUE TITLE
Python package installed successfully.

### ISSUE THREAD

**Issue by extractorpublicidad** [chsh2/nijiGPen#19]
but status = "not installed"

**Comment by b4zz4** [comment]
https://github.com/chsh2/nijiGPen/issues/9

**Comment by chsh2** [comment]
This problem can have different causes depending on the operating system and the way Blender is installed.
#9 is a case on Windows and #18 is a similar problem on MacOS.

If neither of these applies, may I ask about your operating system and the installation path of Blender? Also, the installation logs are helpful, which can be viewed as described here:
https://github.com/chsh2/nijiGPen/wiki/Dependency-Installation#installation-logs

**Comment by chsh2** [comment]
I tend to close this issue for now since there are no updates and similar issues exist.
If the problem still exists and cannot be solved using the above information, please feel free to comment here with more information.
