### ISSUE TITLE
5.0 Severe Installation Error

### ISSUE THREAD

**Issue by loisvonn** [chsh2/nijiGPen#23]
Hello, I've downloaded this onto Blender on the Add-ons section, and came across this error.

I have tried:
- Renaming the file to nijiGPen, nijiGPen-0
- Editing the zip file name
- Renaming the add-on folder
And this error still persists- what do I do?

In any case, this is still a brilliant addon
Any help would be appreciated, thanks!

![image](https://github.com/chsh2/nijiGPen/assets/129149643/929847a9-5688-41d9-8c9c-f6481344ebb0)

**Comment by chsh2** [comment]
It looks like that the Python dependencies are not installed. Did you execute the [installation steps](https://github.com/chsh2/nijiGPen#installation)? 
You may need to run Blender as administrator to install them. Please refer to [this page](https://github.com/chsh2/nijiGPen/wiki/Dependency-Installation).

**Comment by loisvonn** [comment]
It looks like installing it manually through (admin) cmd terminal solved most of the problem and allowed the Dependency Management panel to appear when enabling nijiGPen

Thank you, it works well now!
![image](https://github.com/chsh2/nijiGPen/assets/129149643/0aad6109-9ecf-4227-9592-82f9c4f2e51d)
![image](https://github.com/chsh2/nijiGPen/assets/129149643/a9a5db56-6855-42ba-8b20-e0e1e89c53a5)

**Comment by chsh2** [comment]
The version 0.5.0 seems to have a new bug, leading to the situation that the package can only be manually installed.
I tried to fix it in [v0.5.1](https://github.com/chsh2/nijiGPen/releases/tag/v0.5.1). Please let me know if there are still issues.
