### ISSUE TITLE
Stroke to meshroke to mesh

### ISSUE THREAD

**Issue by figihiuy** [chsh2/nijiGPen#8]
I would like to be able to stroke to mesh only filled areas. 
Generating a mesh from the fill gives good results.
 If you can ignore the line art in the selection option and generate it only with the fill, the task of generating the mesh is easier.

This is especially useful for areas where the line art is not closed.

**Comment by b4zz4** [comment]
@figihiuy In the new version of blender 3.5 you can convert lines into shapes.

**Comment by figihiuy** [comment]
It has come in handy. Thank you for your quick response.
